name: Set Lib Version
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
        with:
          # Fetch the last 2 commits instead of just 1.
          fetch-depth: 2
      - name: 'Get tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Overwrite version.h
        uses: "DamianReeves/write-file-action@master"
        with:
          path: src/version.cpp
          write-mode: overwrite
          contents: |
            #include "AsyncFsWebServer.h" 
            const char* AsyncFsWebServer::getVersion() { 
            	return "${{ steps.previoustag.outputs.tag }}"; 
            }
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Set new version
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
